name: TodoListApp
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  TodoListApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
        type: group
      - path: Resources
        type: group
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.todolistapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: 番茄待办
        CFBundleName: 番茄待办
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  TodoListAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        type: group
    dependencies:
      - target: TodoListApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.example.todolistapptests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TodoListApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TodoListApp"
        BUNDLE_LOADER: "$(TEST_HOST)"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"

schemes:
  TodoListApp:
    build:
      targets:
        TodoListApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TodoListAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  TodoListAppTests:
    build:
      targets:
        TodoListAppTests: all
        TodoListApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TodoListAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
